# Generated by Django 6.0.2 on 2026-02-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da categoria"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição da categoria"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Data de criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data de Modificação"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
