# Generated by Django 6.0.2 on 2026-02-25 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome do Produto"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Preço Unitário do Produto",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data de Modificação"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fk_produto_categoria",
                        to="categorias.category",
                        verbose_name="Categoria do Produto",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "category"],
            },
        ),
    ]
